"""testing

Revision ID: 8093374dc5d4
Revises: 
Create Date: 2020-05-17 02:28:47.450402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8093374dc5d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    x = True

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('Start_time', sa.DATETIME(), nullable=True))
    op.add_column('post', sa.Column('Title', sa.VARCHAR(length=100), nullable=True))
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_start_time'), table_name='post')
    op.alter_column('post', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('post', 'title')
    op.drop_column('post', 'start_time')
    # ### end Alembic commands ###
